# Automatically generated by ../kakoune-lsp/ci/commit-new-release.sh.sh
class KakouneLsp < Formula
  desc "Kakoune Language Server Protocol Client"
  homepage "https://github.com/kakoune-lsp/kakoune-lsp/"
  version "19.0.1"

  if Hardware::CPU.arm?
    url "https://github.com/kakoune-lsp/kakoune-lsp/releases/download/v19.0.1/kakoune-lsp-v19.0.1-aarch64-apple-darwin.tar.gz"
    sha256 "92e3bc805db1c087f2e388724c57f22c2d1727888b1b691ddcf05791bcb71086"
  else
    on_macos do
      url "https://github.com/kakoune-lsp/kakoune-lsp/releases/download/v19.0.1/kakoune-lsp-v19.0.1-x86_64-apple-darwin.tar.gz"
      sha256 "4189e501dc320c3eb666fbd56447f0f9f827d96f5e61fd349d62a36e30143300"
    end
    on_linux do
      url "https://github.com/kakoune-lsp/kakoune-lsp/releases/download/v19.0.1/kakoune-lsp-v19.0.1-x86_64-unknown-linux-musl.tar.gz"
      sha256 "8061d1ee84728a422470893f5bc119bbc36e4216847e822169983065243a3979"
    end
  end

  def install
    bin.install "kak-lsp"
  end

  def caveats
    <<~EOS
      For usage instructions, see https://github.com/kakoune-lsp/kakoune-lsp/blob/v#{version}/README.asciidoc
    EOS
  end

end
