# Automatically generated by ../kakoune-lsp/ci/commit-new-release.sh.sh
class KakouneLsp < Formula
  desc "Kakoune Language Server Protocol Client"
  homepage "https://github.com/kakoune-lsp/kakoune-lsp/"
  version "18.2.0"

  if Hardware::CPU.arm?
    url "https://github.com/kakoune-lsp/kakoune-lsp/releases/download/v19.0.0/kakoune-lsp-v19.0.0-aarch64-apple-darwin.tar.gz"
    sha256 "77a997f390363d5e298fdcdb0ff99019e7b77b0a981f8678e8c602fdf36754cb"
  else
    on_macos do
      url "https://github.com/kakoune-lsp/kakoune-lsp/releases/download/v19.0.0/kakoune-lsp-v19.0.0-x86_64-apple-darwin.tar.gz"
      sha256 "9bad179ca2f5f21305b81ca2d2133ae9ec26bc30d403fe1a480e3913c7ded482"
    end
    on_linux do
      url "https://github.com/kakoune-lsp/kakoune-lsp/releases/download/v19.0.0/kakoune-lsp-v19.0.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "f03583bea106a0c5544aa3dc592d0993653ba940b72ceafcdcd8ea06a0b0a1d5"
    end
  end

  def install
    bin.install "kak-lsp"
  end

  def caveats
    <<~EOS
      For usage instructions, see https://github.com/kakoune-lsp/kakoune-lsp/blob/v#{version}/README.asciidoc
    EOS
  end

end
