# Automatically generated by ../kakoune-lsp/ci/commit-new-release.sh.sh
class KakouneLsp < Formula
  desc "Kakoune Language Server Protocol Client"
  homepage "https://github.com/kakoune-lsp/kakoune-lsp/"
  version "21.0.1"

  if Hardware::CPU.arm?
    url "https://github.com/kakoune-lsp/kakoune-lsp/releases/download/v21.0.1/kakoune-lsp-v21.0.1-aarch64-apple-darwin.tar.gz"
    sha256 "a1b3a56c6269aa056d7d93b8e5cf30843bc12d5f001ba9e5520b81c8f17354ce"
  else
    on_macos do
      url "https://github.com/kakoune-lsp/kakoune-lsp/releases/download/v21.0.1/kakoune-lsp-v21.0.1-x86_64-apple-darwin.tar.gz"
      sha256 "952e9c19b2d433f8a1642e658f558e3fa4b145e3cffdbc02f94974483a9c3dde"
    end
    on_linux do
      url "https://github.com/kakoune-lsp/kakoune-lsp/releases/download/v21.0.1/kakoune-lsp-v21.0.1-x86_64-unknown-linux-musl.tar.gz"
      sha256 "f6c98d4c8f2ba6a59646f7b23fad81699597213a885133d08f3c19b6e1dd34e5"
    end
  end

  def install
    bin.install "kak-lsp"
  end

  def caveats
    <<~EOS
      For usage instructions, see https://github.com/kakoune-lsp/kakoune-lsp/blob/v#{version}/README.asciidoc
    EOS
  end

end
